import { Inter } from "next/font/google";
import Link from 'next/link';
import "./globals.css";
import Navbar from "@/components/Navbar";
import Login from "@/components/Login";

const inter = Inter({ subsets: ["latin"] });
const ram =true;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, team, analytics }) {
  if(ram){
    return(
      <html lang="en">
      <body className={inter.className}>
      <Login />
      </body>
    </html>
    )
  }
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
        <div>
          {children}
          {team}
          {analytics}
        </div>
      </body>
    </html>
  );
}
